//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opm_validation_service.Persistence.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_access_log
    {
        public int id { get; set; }
        public string tdo_user_id { get; set; }
        public System.DateTime tdo_access_time { get; set; }
        public string tdo_ean { get; set; }
    }
}
